name: Show Date and Time

on:
  push:          
  pull_request:  

jobs:
  show-datetime: 
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Moscow
    steps:
      - name: Print current date and time
        run: date
        
